#
module StateConstants
  STATES_WITH_CODES = [
    { state: 'Alabama', state_abbrev: 'AL' },
    { state: 'Alaska', state_abbrev: 'AK' },
    { state: 'Arizona', state_abbrev: 'AZ' },
    { state: 'Arkansas', state_abbrev: 'AR' },
    { state: 'California', state_abbrev: 'CA' },
    { state: 'Colorado', state_abbrev: 'CO' },
    { state: 'Connecticut', state_abbrev: 'CT' },
    { state: 'Delaware', state_abbrev: 'DE' },
    { state: 'Florida', state_abbrev: 'FL' },
    { state: 'Georgia', state_abbrev: 'GA' },
    { state: 'Hawaii', state_abbrev: 'HI' },
    { state: 'Idaho', state_abbrev: 'ID' },
    { state: 'Illinois', state_abbrev: 'IL' },
    { state: 'Indiana', state_abbrev: 'IN' },
    { state: 'Iowa', state_abbrev: 'IA' },
    { state: 'Kansas', state_abbrev: 'KS' },
    { state: 'Kentucky', state_abbrev: 'KY' },
    { state: 'Louisiana', state_abbrev: 'LA' },
    { state: 'Maine', state_abbrev: 'ME' },
    { state: 'Maryland', state_abbrev: 'MD' },
    { state: 'Massachusetts', state_abbrev: 'MA' },
    { state: 'Michigan', state_abbrev: 'MI' },
    { state: 'Minnesota', state_abbrev: 'MN' },
    { state: 'Mississippi', state_abbrev: 'MS' },
    { state: 'Missouri', state_abbrev: 'MO' },
    { state: 'Montana', state_abbrev: 'MT' },
    { state: 'Nebraska', state_abbrev: 'NE' },
    { state: 'Nevada', state_abbrev: 'NV' },
    { state: 'New Hampshire', state_abbrev: 'NH' },
    { state: 'New Jersey', state_abbrev: 'NJ' },
    { state: 'New Mexico', state_abbrev: 'NM' },
    { state: 'New York', state_abbrev: 'NY' },
    { state: 'North Carolina', state_abbrev: 'NC' },
    { state: 'North Dakota', state_abbrev: 'ND' },
    { state: 'Ohio', state_abbrev: 'OH' },
    { state: 'Oklahoma', state_abbrev: 'OK' },
    { state: 'Oregon', state_abbrev: 'OR' },
    { state: 'Pennsylvania', state_abbrev: 'PA' },
    { state: 'Rhode Island', state_abbrev: 'RI' },
    { state: 'South Carolina', state_abbrev: 'SC' },
    { state: 'South Dakota', state_abbrev: 'SD' },
    { state: 'Tennessee', state_abbrev: 'TN' },
    { state: 'Texas', state_abbrev: 'TX' },
    { state: 'Utah', state_abbrev: 'UT' },
    { state: 'Vermont', state_abbrev: 'VT' },
    { state: 'Virginia', state_abbrev: 'VA' },
    { state: 'Washington', state_abbrev: 'WA' },
    { state: 'West Virginia', state_abbrev: 'WV' },
    { state: 'Wisconsin', state_abbrev: 'WI' },
    { state: 'Wyoming', state_abbrev: 'WY' },
    { state: 'American Samoa', state_abbrev: 'AS' },
    { state: 'District of Columbia', state_abbrev: 'DC' },
    { state: 'Washington, D.C.', state_abbrev: 'DC' },
    { state: 'Federated States of Micronesia', state_abbrev: 'FM' },
    { state: 'Guam', state_abbrev: 'GU' },
    { state: 'Marshall Islands', state_abbrev: 'MH' },
    { state: 'Northern Mariana Islands', state_abbrev: 'MP' },
    { state: 'Palau', state_abbrev: 'PW' },
    { state: 'Puerto Rico', state_abbrev: 'PR' },
    { state: 'Virgin Islands', state_abbrev: 'VI' }
  ].freeze

  STATES = STATES_WITH_CODES.map { |state| state[:state] }.freeze
  STATE_CODES = STATES_WITH_CODES.map { |state| state[:state_abbrev] }.freeze

  TERRITORIES = ['American Samoa', 'Guam', 'Northern Mariana', 'Puerto Rico',
                 'U.S. Virgin Islands'].freeze
end
